/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vasthtkrfktxiaiurail"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhc3RodGtyZmt0eGlhaXVyYWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MzgyMDUsImV4cCI6MjA3NzQxNDIwNX0.Q-wUyiJc8IKhO7Yr1BvBEbbyMJ1kbaPxF_-zhYOH3A4"